services:
  db:
    image: supabase/postgres:17.4.1.077
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: supabase_admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      DATABASE_URI: "postgresql://supabase_admin:postgres@db:5432/frontend"
      NODE_ENV: production
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    depends_on:
      - db
    command: ["npm", "run", "deploy"]

volumes:
  db_data:
